import { Hono } from "hono";
import { withUser } from "../db";
import { requireAuth } from "../middleware";
import { buildReportPdf, type PdfSection } from "../utils/pdf";
import {
  getCashflow,
  getExportJob,
  getReportsSummary,
  getSpendingByCategory,
  listExportJobs,
  resolveRange,
  type DateRange,
} from "../queries/reports";
import { listMilestones, listSnapshots } from "../queries/net-worth";

const reportExports = new Hono();

reportExports.get("/", requireAuth, async (c) => {
  const user = c.get("user");
  return c.json({ exports: await listExportJobs(user.user_id) });
});

/**
 * Stateless regenerate-on-download: the stored job row carries the params
 * (template/range); the PDF is rebuilt deterministically on every request â€”
 * nothing is persisted to disk (serverless-safe).
 */
reportExports.get("/:id/download", requireAuth, async (c) => {
  const user = c.get("user");
  const job = await getExportJob(user.user_id, c.req.param("id"));
  if (!job) return c.json({ error: "Not found" }, 404);

  const range: DateRange = resolveRange(
    6,
    job.date_range_start,
    job.date_range_end ?? job.date_range_start
      ? (job.date_range_end ?? isoToday())
      : null
  );

  const sections = await buildDashboardSections(user.user_id, range);
  const pdf = await buildReportPdf({
    title: "MoneyMind Report",
    subtitle: `Period ${range.from} â†’ ${range.to}`,
    footer: "Generated by MoneyMind â€” aggregated figures only.",
    sections,
  });

  return new Response(new Uint8Array(pdf), {
    headers: {
      "content-type": "application/pdf",
      "content-disposition": `attachment; filename="moneymind-report-${range.from}-to-${range.to}.pdf"`,
    },
  });
});

function isoToday(): string {
  return new Date().toISOString().slice(0, 10);
}

/** Shared section builder â€” also used by GET /api/net-worth/report. */
export async function buildDashboardSections(
  userId: number,
  range: DateRange
): Promise<PdfSection[]> {
  const [cashflow, categories, summary, snapshots] = [
    await getCashflow(userId, range),
    await getSpendingByCategory(userId, range).then((rows) => rows.slice(0, 10)),
    await getReportsSummary(userId, range),
    await listSnapshots(userId, range.from, range.to),
  ];

  const sections: PdfSection[] = [];

  sections.push({
    heading: "Summary",
    columns: ["Metric", "Value"],
    rows: [
      ["Total income", summary.total_income.toFixed(2)],
      ["Total expense", summary.total_expense.toFixed(2)],
      ["Net", summary.net.toFixed(2)],
      ["Top category", summary.top_category ?? "-"],
      ["Top merchant", summary.top_merchant ?? "-"],
      ["Budget overruns", summary.budget_overruns],
      ["Debt outstanding", summary.debt_outstanding.toFixed(2)],
    ],
  });

  if (cashflow.length > 0) {
    sections.push({
      heading: "Monthly cash flow",
      columns: ["Month", "Income", "Expense", "Net"],
      rows: cashflow.map((m) => [
        m.month,
        m.income.toFixed(2),
        m.expense.toFixed(2),
        m.net.toFixed(2),
      ]),
    });
  }

  if (categories.length > 0) {
    sections.push({
      heading: "Top spending categories",
      columns: ["Category", "Total", "Txns", "Share %"],
      rows: categories.map((cat) => [
        cat.category,
        cat.total.toFixed(2),
        cat.count,
        cat.pct.toFixed(1),
      ]),
    });
  }

  if (snapshots.length > 0) {
    sections.push({
      heading: "Net worth trend",
      columns: ["Date", "Assets", "Liabilities", "Net worth"],
      rows: snapshots.slice(-24).map((s) => [
        s.date,
        s.assets_total.toFixed(2),
        s.liabilities_total.toFixed(2),
        s.net_worth.toFixed(2),
      ]),
    });
  }

  const milestones = await listMilestones(userId);
  if (milestones.length > 0) {
    sections.push({
      heading: "Net worth milestones",
      columns: ["Label", "Target", "Reached"],
      rows: milestones.map((m) => [
        m.label,
        m.target_amount.toFixed(2),
        m.reached_at ?? "not yet",
      ]),
    });
  }

  return sections;
}

export { reportExports };
