import { beforeEach, describe, expect, it, vi } from "vitest";
import { Hono } from "hono";
const mocks = vi.hoisted(() => ({ query: vi.fn(), session: vi.fn() }));
vi.mock("./db", () => ({ query: mocks.query }));
vi.mock("./session", () => ({ getSessionUserByToken: mocks.session }));
import { requireAuth } from "./middleware";
import { requirePremium } from "./entitlements";
import { membershipGuards } from "./membership-guards";
import { detectSubscriptionAudits } from "./utils/subscription-audits";
beforeEach(() => { mocks.query.mockResolvedValue({ rows: [{ plan_type: "free", billing_cycle: null }] }); mocks.session.mockResolvedValue({ user_id: 1 }); });
describe("entitlements", () => {
  const app = new Hono();
  app.get("/premium", requireAuth, requirePremium, (c) => c.json({ success: true }));
  it("requires authentication", async () => { mocks.session.mockResolvedValue(null); expect((await app.request("/premium")).status).toBe(401); });
  it("denies Starter", async () => { expect((await app.request("/premium")).status).toBe(403); });
  it.each(["monthly", "annual", "lifetime"])("gives %s the identical premium access", async (billing_cycle) => { mocks.query.mockResolvedValue({ rows: [{ plan_type: "premium", billing_cycle }] }); expect((await app.request("/premium")).status).toBe(200); });
  it("does not use billing metadata to grant free users access", async () => { mocks.query.mockResolvedValue({ rows: [{ plan_type: "free", billing_cycle: "lifetime" }] }); expect((await app.request("/premium")).status).toBe(403); });
});
describe("field-level guards", () => {
  const app = new Hono(); app.use("/api/*", membershipGuards);
  app.patch("/api/*", (c) => c.json({ success: true }));
  app.get("/api/users/me/data-copy", (c) => c.json({ success: true }));
  const patch = (path: string, body: unknown) => app.request(path, { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify(body) });
  it("allows in-app preferences", async () => expect((await patch("/api/notification-preferences", { preferences: [{ channel: "in_app", is_enabled: true }] })).status).toBe(200));
  it("blocks mixed batches with email enabled", async () => expect((await patch("/api/notification-preferences", { preferences: [{ channel: "in_app", is_enabled: true }, { channel: "email", is_enabled: 1 }] })).status).toBe(403));
  it("blocks direct email toggles", async () => expect((await patch("/api/notification-preferences/bill_reminder/email", {})).status).toBe(403));
  it("allows disabling email", async () => expect((await patch("/api/notification-preferences", { preferences: [{ channel: "email", is_enabled: false }] })).status).toBe(200));
  it("blocks widget edits", async () => expect((await patch("/api/users/me/settings", { widget_layout: [] })).status).toBe(403));
  it("preserves privacy export access", async () => expect((await app.request("/api/users/me/data-copy")).status).toBe(200));
  it("preserves authentication status", async () => { mocks.session.mockResolvedValue(null); expect((await patch("/api/users/me/settings", {})).status).toBe(401); });
  it("rejects malformed preference entries", async () => expect((await patch("/api/notification-preferences", { preferences: [null] })).status).toBe(400));
});
describe("audit detection", () => {
  const sub = { id: "a", service_name: "Music Plus", amount: 1200, frequency: "annual", category_id: "music", last_used_at: null };
  it("normalizes duplicate names and monthly savings", () => { const results = detectSubscriptionAudits([sub, { ...sub, id: "b", service_name: "music-plus" }]); expect(results).toHaveLength(1); expect(results[0]).toMatchObject({ audit_type: "duplicate", potential_savings: 100 }); });
  it("marks shared categories as possible overlaps", () => expect(detectSubscriptionAudits([sub, { ...sub, id: "b", service_name: "Other" }])[0].audit_type).toBe("overlapping"));
  it("does not invent unused evidence", () => expect(detectSubscriptionAudits([sub])).toEqual([]));
  it("detects unused from explicit old usage", () => expect(detectSubscriptionAudits([{ ...sub, last_used_at: "2025-01-01" }], new Date("2026-09-05"))[0].audit_type).toBe("unused"));
  it("does not mark recently used services", () => expect(detectSubscriptionAudits([{ ...sub, last_used_at: "2026-09-04" }], new Date("2026-09-05"))).toEqual([]));
});
